# Generated by Django 5.0.2 on 2024-03-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoderPE3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('profesión', models.CharField(max_length=60)),
            ],
        ),
    ]
